# Generated by Django 5.1.7 on 2025-09-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0022_parent_parentinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
